language: cpp
compiler: g++
os: linux
sudo: required
script:
  - url=https://github.com/01org/tbb/archive/2018_U2.tar.gz
  - filename=$(basename "$url")
  - wget "$url"
  - tar xzf $filename
  - mv "tbb-2018_U2" ./tbb-2018
  - mode=debug
  - cd ./tbb-2018
  - make
  - cd build
  - filename=$(ls | egrep _$mode) 
  - echo $filename
  - cd $filename
  - chmod 777 tbbvars.sh
  - sed -i -e "s/$filename/linux_$mode/g" tbbvars.sh
  - cd ..
  - mv $filename linux_$mode
  - chmod 777 "linux_$mode/tbbvars.sh"
  - cd ../..
  - mkdir cmake-build-$mode
  - cd cmake-build-$mode
  - cmake ..
  - source "../tbb-2018/build/linux_$mode/tbbvars.sh" && make